### PR TITLE
switch to formik

### PR DESCRIPTION
**Pull request by Akhilesh-pujar**
formik

### CODE REVIEW

**Review by devsubid — CHANGES_REQUESTED** [review]
you just updated the package-lock file but you were assigned to work on the dashboard, please work on the dashboard then create a pull request

**Review by Akhilesh-pujar — COMMENTED** [review]
dashboard-formik

**Review by devsubid — CHANGES_REQUESTED** [review]
on line 180
please convert the handleSubmit function to the onSubmit function, to make it work

**Comment by devsubid** [comment]
and please update your branch first, currently, we are having new update

**Review by devsubid — CHANGES_REQUESTED** [review]
use the camelCase naming convention, and use a meaningful name like FormValidation or something like that

**Review by devsubid — APPROVED** [review]

**Pull request merged**
